name: precompile

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod
    strategy:
      matrix:
        otp_version: [24]

    name: Linux - OTP ${{ matrix.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: 1.15

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip \
            gcc g++ \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-riscv64-linux-gnu g++-riscv64-linux-gnu \
            gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu \
            gcc-s390x-linux-gnu g++-s390x-linux-gnu

      - name: Precompile
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix deps.get
          mix elixir_make.precompile

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
            cache/*.sha256

  macos:
    runs-on: ${{ matrix.job.runs-on }}
    env:
      MIX_ENV: prod
      ELIXIR_VERSION: "1.16.0"
      OTP_VERSION: ${{ matrix.job.otp_version }}
      CC_PRECOMPILER_PRECOMPILE_ONLY_LOCAL: "true"
    strategy:
      matrix:
        job:
          - { otp_version: "25.3.2.8", runs-on: macos-13, arch: "x86_64" }
          - { otp_version: "25.3.2.8", runs-on: macos-14, arch: "aarch64" }

    name: ${{ matrix.job.arch }}-apple-drawin - OTP ${{ matrix.job.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OTP and Elixir
        run: |
          curl -fsSO https://elixir-lang.org/install.sh
          sh install.sh "elixir@${ELIXIR_VERSION}" "otp@${OTP_VERSION}"

      - name: Precompile
        run: |
          export OTP_MAIN_VER="${OTP_VERSION%%.*}"
          export PATH=$HOME/.elixir-install/installs/otp/${OTP_VERSION}/bin:$PATH
          export PATH=$HOME/.elixir-install/installs/elixir/${ELIXIR_VERSION}-otp-${OTP_MAIN_VER}/bin:$PATH

          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"

          mix local.hex --force
          mix local.rebar --force
          
          mix deps.get
          mix elixir_make.precompile

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
            cache/*.sha256
